#dubbo:
#  application:
#    name: common.storage.king_client
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: zk-registry
#    address: zookeeper://120.46.194.37:2181
#  config-center:
#    address: zookeeper://120.46.194.37:2181
#  metadata-report:
#    address: zookeeper://120.46.194.37:2181
